[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer(\"all-MiniLM-L6-v2\")'"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "always"
restartPolicyMaxRetries = 3
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
ENVIRONMENT = "production"
MODEL_CACHE_DIR = "/app/models"